### ISSUE TITLE
Problems with other FTDI adapters connected

### ISSUE THREAD

**Issue by electrokean** [petersdw1/BattLab-One#11]
I hit problems (hangs) with multiple FTDI adapters connected at startup, as the grep on list_ports selects the wrong one.  It assumes only a single VID:PID match, and thus tries to establish a connection to other equipment with no way to cancel.

I also hit an issue with one adapter that had a single digit serial number - this stopped me running the precompiled code.  I had to set up python dev environment to track down the failure.  I'll submit a simple PR to work around this.

**Comment by electrokean** [comment]
Is there a reason (cross platform compatibilty) that you needed the grep on the port list?
https://github.com/petersdw1/Battlab-One/blob/e4eb4a6a05422b6fdc52cb1a21500bbca6068752/BattLab_One_V1_0_9.py#L395
Couldn't the line just be:
`com_port = p.device`

This plus PR https://github.com/petersdw1/Battlab-One/pull/12 fix my current issues starting the app on Windows.

**Comment by electrokean** [comment]
Well I messed up my fork for PR #12 
I have split it into two new PRs #13 and #14 instead

**Comment by petersdw1** [comment]
Hi Kean, I merged your PR into release V1.0.9.  Can you test and see if its working for you now?

**Comment by electrokean** [comment]
I've tested 1.0.9 and 1.1.0 and this works much better now.
