### ISSUE TITLE
Trigger PSU on capture + Ext Trig Crashes Battlab

### ISSUE THREAD

**Issue by drphil3d** [petersdw1/BattLab-One#20]
- Selecting Trigger PSU on Capture along with Ext Trig then clicking arm crashes the program.
- Turning PSU output on then clicking Capture Active - Not Responding - Must be closed using task manager.

Trying to save a capture results in the program becomes unresponsive and crashing.

Windows 10 x64
BattLab One V1.1.1
Firmware Version 1.003

**Comment by petersdw1** [comment]
Hi Philip,

Hope all is well (besides the BL1 issue). Can you tell me more about your
test setup? What are you triggering on? The reason I ask is that if you
don't have a clean trigger signal the BattLab-One can hang/timeout.

Doug Peters

dpeters@bluebird-labs.com
www.bluebird-labs.com

**Comment by petersdw1** [comment]
Patrick if you are still experiencing issues please contact me at dpeters@bluebird-labs.com.
