### ISSUE TITLE
Cannot connect to BattLab-One (Windows 10)

### ISSUE THREAD

**Issue by chrisb2** [petersdw1/BattLab-One#23]
Windows 10 (ASUS Zenbook, Windows version 21H1, fully updated)
BattLab v1.2.3 (but UI shows 1.1.1 in top left)

With BattLab plugged into my laptop, in BattLab application Connect->Select COM does not show any com ports and clicking refresh makes no difference. In Device Manager it shows up under Other Devices but status says "The drivers for this device are not installed. (Code 28) There are no compatible drivers for this device.":
<img width="126" alt="battlab-device" src="https://user-images.githubusercontent.com/3087703/127754814-965dac29-3c35-42ce-a174-a2e99d11438f.PNG">
How do I fix this?

thanks,
Chris

**Comment by chrisb2** [comment]
I have found I can connect to an esp32 running MicroPython OK, so seems like actual hardware is good.

**Comment by chrisb2** [comment]
I got this working in the end, by uninstalling and re-installing device drivers and restarting, but not quite sure precisely what fix it!

**Comment by petersdw1** [comment]
Hi Chris,

The only thing I can think of is that the driver got corrupted somehow.  I
use Zaig to install the *libusb-win32 (v1.2.6.0) *driver.

https://zadig.akeo.ie/

then install the FTDI drivers using below:

https://www.driverscloud.com/en/services/GetInformationDriver/71116-58653/ftdi-chip-cdm21228-setupzip

Let me know if that works!

Doug Peters
***@***.***
www.bluebird-labs.com
+1 (651) 272-9938
