### ISSUE TITLE
Battlab not exiting when closed

### ISSUE THREAD

**Issue by vangalvin** [petersdw1/BattLab-One#3]
Im not 100% sure if this is an issue with the windows version of Battlab-One or if its an issue with my Win7 Pro
Essentially when you run Battlab then exit out the process remains running in Taskmanager under proceses. I had been trying to sample a microcontroller and had an issue where Battlab seemed to lock up. It turned out that each time I loaded and closed it another instace would be started under the process tree and althoug the application had previously been exited the remaining process would interfere with the next time the application had been run.

![TaskManagerScreenshot](https://user-images.githubusercontent.com/11986968/91624686-adc74b00-e9f5-11ea-8f97-a2bf4f8aef93.png)

**Comment by petersdw1** [comment]
Great feedback thanks Boris.  I'll have to take a look once I get through
my backlog of orders this week.

Doug

**Comment by perja12** [comment]
Created a PR with fix for this here: https://github.com/petersdw1/Battlab-One/pull/7

**Comment by petersdw1** [comment]
Excellent thank you Per Thomas!  Boris, I just published a  new release, 1.0.7 that merges Per Thomas' fix.
Thanks,
Doug

**Comment by petersdw1** [comment]
...now in release 1.0.8...

**Comment by petersdw1** [comment]
Hi Boris can you confirm if this is working for you now and close the issue if it is?

Thanks,
Doug
