### ISSUE TITLE
Missing Counts.

### ISSUE THREAD

**Issue by vangalvin** [petersdw1/BattLab-One#4]
I have been trying to pull the data out of the raw log and use that for creating power usage prifiles. Exporting the data in to a spreadsheet I noticed that the sample counts were not lining up.

For example
`219,0.04412
220,0.04412
222,0.02941
223,0.02941
224,0.04412`

notice 221 is missing, sampling over 60 seconds the csv had 60718 entries according to sample count however when imported in to a spreadsheet there were only 67992 entries meaning some of the data was missing. 

I only discovered this when I was trying to work out how to convert the count in to time and create a chart based on peak usage over time. 

For the above above example and thankfully in my case its on the sleep side of a sample however if this was to appear during the wake cycle this would throw off the figures dramaticaly.

**Comment by petersdw1** [comment]
Good catch Boris. I do some software filtering of any noise from the INA233
and it probably is tossing the noise sample but not also tossing the count.
I can fix in the next release. Should be in about a week.

Doug

**Comment by petersdw1** [comment]
Hi Boris, this should now be working properly in V1.0.9.  Can you test on your side and see if its working ok?
