### ISSUE TITLE
// Spurious Values //

### ISSUE THREAD

**Issue by salvagione** [petersdw1/BattLab-One#9]
During transmits I'm seeing values that are much higher then the LDO on the device can provide and don't show up on my DMM or PSU.

![2020-09-23_16-51-42](https://user-images.githubusercontent.com/7918493/94085655-947ba980-fdbd-11ea-9d2c-1f67972eda49.png)

**Comment by petersdw1** [comment]
This is either a true noise reading from the INA233 in which case increasing the number of samples to use for averaging might fix(see image below), or it's an artifact of the large 1000uF capacitor I have on the output (which I am thinking of removing in future designs).

![image](https://user-images.githubusercontent.com/4383161/94195448-a2423500-fe78-11ea-96fb-0d0abf5bb24c.png)
